### ISSUE TITLE
where's the jsonl files when calculate the scores

### ISSUE THREAD

**Issue by renatz** [KwanWaiChung/MT-Eval#3]
```
code\MT-Eval\calculate_score.py", line 209, in <module>
    for row in open(
FileNotFoundError: [Errno 2] No such file or directory: '/kfdata05/kf_grp/wckwan/Multi-Turn-Benchmark/our_data/global-inst_conv_v1.0.jsonl'
```

Is the corresponding relationship right?
`/kfdata05/kf_grp/wckwan/Multi-Turn-Benchmark/our_data/global-inst_conv_v1.0.jsonl`
to
`recollection_multi_global-inst.jsonl`

`/kfdata05/kf_grp/wckwan/Multi-Turn-Benchmark/our_data/global-inst-single_conv_v1.0.jsonl`
to
`recollection_single_global-inst.jsonl`

**Comment by KwanWaiChung** [comment]
Hi, that's actually some unnecessary code that I forgot to delete after refactoring the code. It's fixed in the latest commit.
