### ISSUE TITLE
Question about the follow-up data

### ISSUE THREAD

**Issue by ridiculouz** [KwanWaiChung/MT-Eval#4]
Hi there,
Congrats on this great work! I have one particular question about the follow-up tasks. I've noticed that the user queries are fixed for all models and dialogue tracks. How can you ensure the fluency and coherence of conversations? User's questions may not refer to previous assistant's responses.

**Comment by KwanWaiChung** [comment]
Hi! In the follow-up tasks, we fix both the user queries and the assistant's responses in the dialogue history. This means we do not include generated responses in the dialogue history, unlike in other tasks. The purpose is to maintain fluency, as you mentioned. Hope that helps!
